-- ============================================================
-- SPEAKFLAKE: All Table Definitions
-- ============================================================

-- =========================
-- SCHEMA: CORE
-- =========================

CREATE OR REPLACE TABLE SPEAKFLAKE_DB.CORE.SALES_FACT (
    SALE_ID         NUMBER(38,0) NOT NULL,
    REGION          VARCHAR(50),
    COUNTRY         VARCHAR(50),
    SALES_REP       VARCHAR(100),
    PRODUCT         VARCHAR(100),
    CATEGORY        VARCHAR(50),
    DEAL_VALUE      NUMBER(15,2),
    DEAL_STATUS     VARCHAR(20),
    QUARTER         VARCHAR(10),
    FISCAL_YEAR     NUMBER(38,0),
    CLOSE_DATE      DATE,
    PRIMARY KEY (SALE_ID)
) COMMENT = 'Sales deal fact table — every opportunity with region, product, value, and status';

CREATE OR REPLACE TABLE SPEAKFLAKE_DB.CORE.SALES_REPS (
    REP_ID      NUMBER(38,0) NOT NULL,
    REP_NAME    VARCHAR(100),
    REGION      VARCHAR(50),
    TEAM        VARCHAR(50),
    HIRE_DATE   DATE,
    IS_ACTIVE   BOOLEAN,
    PRIMARY KEY (REP_ID)
) COMMENT = 'Sales rep roster — name, region, team assignment, and active status';

CREATE OR REPLACE TABLE SPEAKFLAKE_DB.CORE.REGION_TARGETS (
    REGION        VARCHAR(50),
    QUARTER       VARCHAR(10),
    FISCAL_YEAR   NUMBER(38,0),
    TARGET_VALUE  NUMBER(15,2),
    ACTUAL_VALUE  NUMBER(15,2)
) COMMENT = 'Quarterly revenue targets vs actuals by region';

-- =========================
-- SCHEMA: MEMORY
-- =========================

CREATE OR REPLACE TABLE SPEAKFLAKE_DB.MEMORY.SESSIONS (
    SESSION_ID   VARCHAR(36) NOT NULL,
    USER_NAME    VARCHAR(100),
    CREATED_AT   TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    LAST_ACTIVE  TIMESTAMP_NTZ(9),
    STATUS       VARCHAR(20) DEFAULT 'ACTIVE',
    TITLE        VARCHAR(200),
    PRIMARY KEY (SESSION_ID)
) COMMENT = 'Tracks user conversation sessions — one row per chat session';

CREATE OR REPLACE TABLE SPEAKFLAKE_DB.MEMORY.CONVERSATION_HISTORY (
    TURN_ID      NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SESSION_ID   VARCHAR(36),
    TURN_NUMBER  NUMBER(38,0),
    ROLE         VARCHAR(10),
    MESSAGE      VARCHAR(16777216),
    INTENT_TYPE  VARCHAR(30),
    CONFIDENCE   FLOAT,
    CREATED_AT   TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TURN_ID)
) COMMENT = 'Full conversation log — every user/assistant turn with intent classification';

CREATE OR REPLACE TABLE SPEAKFLAKE_DB.MEMORY.SESSION_RESULTS (
    RESULT_ID       NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SESSION_ID      VARCHAR(36),
    TURN_NUMBER     NUMBER(38,0),
    QUESTION        VARCHAR(16777216),
    SQL_GENERATED   VARCHAR(16777216),
    RESULT_SUMMARY  VARCHAR(16777216),
    RESULT_JSON     VARIANT,
    CREATED_AT      TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RESULT_ID)
) COMMENT = 'Persists SQL outputs and plain-English summaries for conversational re-injection';

CREATE OR REPLACE TABLE SPEAKFLAKE_DB.MEMORY.INSIGHT_DOCUMENTS (
    DOC_ID      NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SESSION_ID  VARCHAR(36),
    TITLE       VARCHAR(200),
    CONTENT     VARCHAR(16777216),
    USER_NAME   VARCHAR(100),
    CREATED_AT  TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DOC_ID)
) COMMENT = 'Board-ready executive insight documents generated from analytics sessions';

-- Dynamic Table: SESSION_SUMMARY
CREATE OR REPLACE DYNAMIC TABLE SPEAKFLAKE_DB.MEMORY.SESSION_SUMMARY
  TARGET_LAG = '1 minute'
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
  WAREHOUSE = SPEAKFLAKE_WH
AS
SELECT
    s.SESSION_ID,
    s.USER_NAME,
    s.STATUS,
    s.TITLE,
    MIN(CASE WHEN c.ROLE = 'USER' THEN c.MESSAGE END) AS FIRST_QUESTION,
    MAX(CASE WHEN c.ROLE = 'USER' AND c.TURN_NUMBER = latest.MAX_USER_TURN THEN c.MESSAGE END) AS LAST_QUESTION,
    COUNT(c.TURN_ID) AS TURN_COUNT,
    s.CREATED_AT,
    s.LAST_ACTIVE
FROM SPEAKFLAKE_DB.MEMORY.SESSIONS s
LEFT JOIN SPEAKFLAKE_DB.MEMORY.CONVERSATION_HISTORY c
    ON s.SESSION_ID = c.SESSION_ID
LEFT JOIN (
    SELECT SESSION_ID, MAX(TURN_NUMBER) AS MAX_USER_TURN
    FROM SPEAKFLAKE_DB.MEMORY.CONVERSATION_HISTORY
    WHERE ROLE = 'USER'
    GROUP BY SESSION_ID
) latest ON s.SESSION_ID = latest.SESSION_ID
GROUP BY s.SESSION_ID, s.USER_NAME, s.STATUS, s.TITLE, s.CREATED_AT, s.LAST_ACTIVE;

-- Dynamic Table: ACTIVE_SESSION_CONTEXT
CREATE OR REPLACE DYNAMIC TABLE SPEAKFLAKE_DB.MEMORY.ACTIVE_SESSION_CONTEXT
  TARGET_LAG = '1 minute'
  REFRESH_MODE = AUTO
  INITIALIZE = ON_CREATE
  WAREHOUSE = SPEAKFLAKE_WH
AS
SELECT
    s.SESSION_ID,
    s.USER_NAME,
    s.LAST_ACTIVE,
    ARRAY_SLICE(
        ARRAY_AGG(c.MESSAGE) WITHIN GROUP (ORDER BY c.TURN_NUMBER DESC),
        0, 5
    ) AS LAST_5_TURNS,
    COUNT(c.TURN_ID) AS TOTAL_TURNS,
    MAX(CASE WHEN r.RN = 1 THEN r.RESULT_SUMMARY END) AS LAST_RESULT_SUMMARY
FROM SPEAKFLAKE_DB.MEMORY.SESSIONS s
LEFT JOIN SPEAKFLAKE_DB.MEMORY.CONVERSATION_HISTORY c
    ON s.SESSION_ID = c.SESSION_ID
LEFT JOIN (
    SELECT SESSION_ID, RESULT_SUMMARY,
           ROW_NUMBER() OVER (PARTITION BY SESSION_ID ORDER BY CREATED_AT DESC) AS RN
    FROM SPEAKFLAKE_DB.MEMORY.SESSION_RESULTS
) r ON s.SESSION_ID = r.SESSION_ID AND r.RN = 1
WHERE s.STATUS = 'ACTIVE'
GROUP BY s.SESSION_ID, s.USER_NAME, s.LAST_ACTIVE;

-- =========================
-- SCHEMA: SIMULATION
-- =========================

CREATE OR REPLACE TABLE SPEAKFLAKE_DB.SIMULATION.SIM_LOG (
    SIM_ID          NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SESSION_ID      VARCHAR(36),
    CLONE_NAME      VARCHAR(200),
    SOURCE_TABLE    VARCHAR(200),
    SCENARIO_DESC   VARCHAR(16777216),
    BASELINE_JSON   VARIANT,
    SIM_RESULT_JSON VARIANT,
    STATUS          VARCHAR(20),
    CREATED_AT      TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT    TIMESTAMP_NTZ(9),
    PRIMARY KEY (SIM_ID)
) COMMENT = 'What-if simulation tracker — clone lifecycle, baseline vs scenario comparisons';

-- =========================
-- SCHEMA: APP
-- =========================

CREATE OR REPLACE TABLE SPEAKFLAKE_DB.APP.ERROR_LOG (
    ERROR_ID        NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SESSION_ID      VARCHAR(36),
    PROCEDURE_NAME  VARCHAR(100),
    ERROR_MESSAGE   VARCHAR(16777216),
    USER_NAME       VARCHAR(100),
    CREATED_AT      TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ERROR_ID)
);

CREATE OR REPLACE TABLE SPEAKFLAKE_DB.APP.APP_CODE_STAGING (
    FILE_NAME  VARCHAR(16777216),
    CHUNK_NUM  NUMBER(38,0),
    CONTENT    VARCHAR(16777216)
);

CREATE OR REPLACE TABLE SPEAKFLAKE_DB.APP.BENCHMARK_RESULTS (
    TEST_ID         NUMBER(38,0),
    VERSION         VARCHAR(10),
    QUESTION        VARCHAR(500),
    START_TS        TIMESTAMP_NTZ(9),
    END_TS          TIMESTAMP_NTZ(9),
    DURATION_MS     NUMBER(38,0),
    CONFIDENCE      FLOAT,
    INTENT_TYPE     VARCHAR(50),
    RESPONSE_LENGTH NUMBER(38,0),
    SUCCESS         BOOLEAN
);
